### PR TITLE
Synchronize the lookup-and-define-class logic in blackbird

### LINKED ISSUE #169: Blackbird fails with LinkageError when the same class is used across two separate classloaders
The new Blackbird module has an issue when it is used to serialise the same class, but across two separate classloaders.

eg. we are serialising class a.b.c from an ObjectMapper that is configured to use Blackbird, from within a library.  CrossLoader access does it's thing, and:
* attempts to instantiate class a.b.c$$JacksonBlackbirdAccess
* ClassNotFoundException is thrown, and this instance of CrossLoader attempts to define it

Next, we attempt to deserialise from an ObjectMapper that is configured to use Blackbird, but from within the main application.  The classloader is different.  CrossLoader again attempts to do it's thing, and:
* attempts to instantiate class a.b.c$$JacksonBlackbirdAccess
* ClassNotFoundException is thrown again (because this classloader doesn't have it, and nor does the parent classloader), and this other instance of CrossLoader attempts to define it
* defineClass fails, as the parent ClassLoader already has it defined

Seems to me like your classname - JacksonBlackbirdAccess - cannot be static, but must include an object reference to the current classloader?  ie. allow each copy of JacksonBlackbird CrossLoader to have it's own separate definition of your helper class.

an example stacktrace:
```
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.LinkageError: loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) attempted duplicate class definition for a.b.c.$$JacksonBlackbirdAccess.
	at app//org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at app//org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at app//org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at app//org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3060)
	at app//a.b.c.runSomeTest(c.java:78)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:92)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at app//org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base@11.0.3/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base@11.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.LinkageError: loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) attempted duplicate class definition for a.b.c.$$JacksonBlackbirdAccess.
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2123)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	at com.fasterxml.jackson.module.blackbird.CrossLoaderAccess.accessClassIn(CrossLoaderAccess.java:125)
	at com.fasterxml.jackson.module.blackbird.CrossLoaderAccess.grantAccess(CrossLoaderAccess.java:94)
	at com.fasterxml.jackson.module.blackbird.CrossLoaderAccess.apply(CrossLoaderAccess.java:83)
	at com.fasterxml.jackson.module.blackbird.CrossLoaderAccess.apply(CrossLoaderAccess.java:11)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.createProperty(BBSerializerModifier.java:109)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.lambda$findProperties$0(BBSerializerModifier.java:67)
	at com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$runnable$0(Unchecked.java:31)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.findProperties(BBSerializerModifier.java:68)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.changeProperties(BBSerializerModifier.java:52)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:414)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:294)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:239)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1443)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:544)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:822)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
```

### PR DESCRIPTION
**Pull request by josephlbarnett**
If blackbird attempts to access/define a new class concurrently,
it can hit a race condition between attempting to access it and
defining it when that fails.  If it does fail, enter a synchronized
block and try again before defining the access class.

Should fix #169

### CODE REVIEW

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java [hunk 1]
```diff
@@ -109,24 +109,29 @@ private static Class<?> accessClassIn(MethodHandles.Lookup lookup) throws IOExce
...
-        for (int b : FOOTER) {
-            dataOut.writeByte(b);
-        }
-        try {
-            return (Class<?>) DEFINE_CLASS.invokeExact(lookup, classBytes.toByteArray());
-        } catch (RuntimeException | Error | IOException | ReflectiveOperationException e) {
-            throw e;
-        } catch (Throwable e) {
-            throw new RuntimeException(e);
+        synchronized(CrossLoaderAccess.class) {
```
Comment (josephlbarnett) [inline blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:112]: there may be a narrower thing to synchronize on ? (pkg.getName().intern() perhaps?)

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java [hunk 2]
```diff
@@ -109,24 +109,29 @@ private static Class<?> accessClassIn(MethodHandles.Lookup lookup) throws IOExce
...
+            try {
+                return Class.forName(pkg.getName() + "." + CLASS_NAME, true, lookup.lookupClass().getClassLoader());
+            } catch (ClassNotFoundException ign) { }
```
Comment (josephlbarnett) [inline blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:115]: "try again" logic is attempting to do double checked locking -- I think that's ok in this case but could always use more eyes on those attempts.  Could also remove the unsynchronized reflection and just do everything in a sync block?

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java [hunk 3]
```diff
@@ -109,24 +109,29 @@ private static Class<?> accessClassIn(MethodHandles.Lookup lookup) throws IOExce
...
+            }
+            dataOut.writeUTF(fqcn);
+            for (int b : FOOTER) {
+                dataOut.writeByte(b);
+            }
+            try {
+                return (Class<?>) DEFINE_CLASS.invokeExact(lookup, classBytes.toByteArray());
+            } catch (RuntimeException | Error | IOException | ReflectiveOperationException e) {
+                throw e;
+            } catch (Throwable e) {
```
Comment (cowtowncoder) [inline blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:132]: Could be `Exception` although I suppose does not make much difference as preceding catch block already handles `RuntimeException` and `Error`.

**Comment by cowtowncoder** [comment]
Can't find anything wrong but I'll let @stevenschlansker review as he's the author of Blackbird module should know best.

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java (hunk 3 above)
Comment (josephlbarnett) [reply blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:132]: possibly.  I didn't want to mess with the existing code much so left it as is other than surrounding with synchronization....

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java (hunk 2 above)
Comment (stevenschlansker) [reply blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:115]: I think it's nice to avoid unnecessary synchronization in the common path - where the class is already loaded.
It's a little unfortunate that this `Class.forName` expression is repeated, but factoring it out might not be much clearer.

What about computing the className and fetching classLoader once, stash them in local vars - then at least we don't do the string concatenation twice unnecessarily.

**Review by stevenschlansker — APPROVED** [review]
Looks good to me. One minor potential change suggested.

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java (hunk 3 above)
Comment (stevenschlansker) [reply blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:132]: `invokeExact` declares `throws Throwable` and since it's possible to declare your own subtype of `Throwable`, the `RuntimeException | Error` doesn't actually cover all possible types. So I think making this change would result in a compiler error. Feel free to play around with it though and see if you can do better!

**Comment by josephlbarnett** [comment]
updated per @stevenschlansker's suggestions.  would be good to get this in 2.13 as well once accepted, anything I can do to help with that?

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java (hunk 3 above)
Comment (cowtowncoder) [reply blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:134]: Interesting! Did not realize that someone would mark `Throwable` to be thrown -- don't recall ever seeing that -- but if so, yes, that makes sense.
(also don't remember ever seeing custom `Throwable` sub-class but now I know :) ).

**Comment by cowtowncoder** [comment]
@josephlbarnett For 2.13, it'd be easier if PR was based on 2.13. I can try cherry-picking if that is too much work.

My only concern is wrt safety of the fix, but it seems low-risk enough. It'd go in 2.13.3 which should get out quite soon, as well.

**Comment by josephlbarnett** [comment]
#173 is a 2.13 cherry-pick of this commit

**Comment by cowtowncoder** [comment]
Not sure what gives, but JDK 11 fails with one test.

File: blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java (hunk 3 above)
Comment (stevenschlansker) [reply blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java:134]: This is because `invokeExact` represents an arbitrary method call, with unknown `throws` declared. So since you can call a method that might `throws Throwable`, so too `invokeExact` must handle this possibility.

This was not needed in classic reflection, since any thrown exception was wrapped in an `InvocationTargetException`. But, this didn't end up always being good - for example if you wrapped an unexpected `Error` often the exception handling would get very confusing.

**Comment by josephlbarnett** [comment]
> Not sure what gives, but JDK 11 fails with one test.

I see the test failing both before and after this change?  not sure what's happened there

**Comment by cowtowncoder** [comment]
@josephlbarnett that makes sense. And yes, I can reproduce the fail locally.

I think this was hidden by having JDKs 8 and 14 tested on CI (not 11). But since 14 was dropped by Github it seems (not sure why), changed to 8 and 11 exposing the problem.
